AUTOBOX_VERSION_MAJOR := 1
AUTOBOX_VERSION_MINOR := 0

AUTOBOX_BUILD_DATE := $(shell date -u +%Y%m%d)

ifndef AUTOBOX_BUILDTYPE
    AUTOBOX_BUILDTYPE := UNOFFICIAL
endif

AUTOBOX_VERSION := $(AUTOBOX_VERSION_MAJOR).$(AUTOBOX_VERSION_MINOR)-$(AUTOBOX_BUILD_DATE)-$(AUTOBOX_BUILDTYPE)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.autobox.version=$(AUTOBOX_VERSION) \
    ro.autobox.build.date=$(AUTOBOX_BUILD_DATE) \
    ro.autobox.buildtype=$(AUTOBOX_BUILDTYPE)
